### ISSUE TITLE
Missing activity_type in NonTradeActivity

### ISSUE THREAD

**Issue by zhangbanger** [alpacahq/alpaca-docs#13]
https://github.com/alpacahq/alpaca-docs/blob/4a250e031056eb0878ccfce10d99e36c35758795/oas/broker/openapi.yaml#L1248

is missing the activity type field:

https://alpaca.markets/docs/api-references/broker-api/accounts/account-activities/#attributes-1

**Comment by drew887** [comment]
Hey sorry about the delay on this one, you are correct both TradeActivity and NonTradeActivity are missing the `activity_type` field.

the short answer: Please only use the `Activity` model and ignore `TradeActivity` and `NonTradeActivity` where possible for now.

long answer:  This is because currently we have the inheritance model reversed between these models and their parent `Activity` model which is where the field `activity_type` is defined. In reality it should be that we specify it so that Activity is a baseclass that TradeActivity and NonTradeActivity extend it with oas `allOf`'s and Activity defines a discriminator field (in this case `activity_type`), however We ran into some issues when using these specs to generate code for endpoints that return a mix of TradeActivity and NonTradeActivity (namely `/v1/accounts/activities`) the openapi-generator tool doesn't handle these cases well currently so we resorted to reverting the inheritance model to what we have now where the base Activity model just composes all the fields of `TradeActivity` and `NonTradeActivity` and we have the endpoints defined to return `Activity` models.

That is understandably confusing and we should add warnings to these models that our current advice is to in the meantime ignore TradeActivity and NonTradeActivity and just rely on the Activity model everywhere.

**Comment by zhangbanger** [comment]
Understood - thanks for explaining!
